import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

import "./globals.css";
import SideBar from "@/components/SideBar";
import NavBar from "@/components/NavBar";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  style: ["italic", "normal"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <main className="flex min-h-screen ">
          <aside className="  ">
            <SideBar />
          </aside>
          <div className="flex-1 bg-blue-50">
            <NavBar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
